<?php
/*
 * sklhotspot.inc
 *
 * part of skyron (https://www.skyronfirewall.com)
 * Copyright (c) 2005-2021 Heraklet Bilisim Teknolojileri Ltd. Sti. 
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

require_once('certs.inc');
require_once('config.inc');
require_once('filter.inc');
require_once('globals.inc');
require_once('pkg-utils.inc');
require_once('service-utils.inc');
require_once('util.inc');

// configuration settings
/*
 * Package install/uninstall
 */


/*
 * Reports
 */

/* Configure scheduled reports updates via cron */

/*
 * Input validation
 * Check required Squid configuration and provide instructions to users,
 * instead of trying to mess with 's settings directly.
 */

?>
