#!/usr/bin/env sh
L_WELCOME="5651 LOG Kurulumuna hosgeldiniz 
Bu isleme baslamadan once sisteminizin yedegini almayi unutmayin !! 
Sisteminize gelebilecek zararlardan hic bir sekilde meshul degiliz. 
Kurulum ile ilgili kayitlar ${OUTPUT_IMZA_LOG} dosyasina yazilacaktir.
cat ${OUTPUT_IMZA_LOG} |more 
komutu ile kurulum detaylarini inceleyebilirsiniz.
Iptal etmek icin Ctrl+C yapin."
L_IMZALA_START="5651 Imzalama basliyor..."
L_IMZALA_STOP="Imzalama Bitti..."
L_OK=" [Tamam]"
L_STARTING="Sistem Kurulum Basliyor..."
L_ISTARTING="5651 LOG Imzalama Basliyor..."
L_CLEAN="Temizlik Yapiliyor..."
L_ZAMAN="===> Zaman Ayarlaniyor..."
L_SYSTEM_LOG="===> SYSTEM Log imzalaniyor..."
L_PORTAL_LOG="===> PORTAL Loglari imzalaniyor..."
L_DHCPH_LOG="===> DHCP Log Hazirlaniyor..."
L_DHCP_LOG="===> DHCP Log imzalaniyor..."
L_PROXY_LOG="===> PROXY Log imzalaniyor..."
L_SYSLOG_LOG="===> SYSLOG Log imzalaniyor..."
L_LOGK="===> LOG Kaydi yapiliyor..."
L_PFSETTINGS="Pfsense Ayarlari yapiliyor..."
L_CRONALREADYINSTALLED="Cron Daha önce yüklenmiş..."
L_CRONINSTALL="Cron Yükleniyor..."
L_CREATCER="Certifika olusturuluyor..."
L_TESTCREATCER="Test islemi basliyor..."
L_SSL_CN="DNS Adi"
L_SSL_EMAIL="Email"
L_SSL_O="Firma Adi"
L_SSL_C="U_KOD"
L_SSL_ST="ULKE"
L_SSL_L="SEHIR"

